name: build-windows
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: |
          choco install ninja
          
      - name: Get Skia
        run: |
          mkdir cmake\skia
          curl -L -o skia.zip https://github.com
          tar -xf skia.zip -C cmake/skia

      - name: Build Aseprite
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DLAF_BACKEND=skia -DSKIA_DIR=cmake/skia -DSKIA_LIBRARY_DIR=cmake/skia/out/Release-x64
          cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-Windows
          path: build/bin/
